### ISSUE TITLE
Build issue - modelmesh need buildId to build a new image

### ISSUE THREAD

**Issue by Jooho** [opendatahub-io/modelmesh#28]
ModelMesh needs buildId to work properly but openshift-ci can not set it dynamically. Without the buildId, modelmesh runtime always failed. 

To build from a Dockerfile alone, this buildID must be dynamically generated and used in the Dockerfile. You can use a script to do this. The following command is for building modelmesh image so you can refer this.

~~~
GIT_COMMIT=$(git rev-parse HEAD)
BUILD_ID=$(date '+%Y%m%d')-$(git rev-parse HEAD | cut -c -5)
IMAGE_TAG_VERSION=0.11.0-alpha
IMAGE_TAG=${IMAGE_TAG_VERSION}-$(git branch --show-current)_${BUILD_ID}

docker build -t quay.io/opendatahub/modelmesh:${IMAGE_TAG_VERSION} \
    --build-arg imageVersion=${IMAGE_TAG} \
    --build-arg buildId=${BUILD_ID} \
    --build-arg commitSha=${GIT_COMMIT} . 
~~~

**Comment by israel-hdez** [comment]
Fixed on #32 .
